version: "3"
services: 
    db:
        build:
            context: ./db
        ports:
            - "13306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        container_name: "mysql5.7-jp"
        volumes: 
            - ./initdb/:/docker-entrypoint-initdb.d
    web:
        build: 
            context: ./spring-boot-docker-App
        ports: 
            - 8080:8080
        privileged: true
        tty: true
        links:
            - db
        volumes: 
            - ./spring-boot-docker-App/:/var/www/spring-boot/

        container_name: "spring-boot-docker-App"